In [5]:
# demonstrating C-type vs python
fruits = ['oranges','pineapples', 'apples','bananas','strawberries']
numbers = [1,2,3,4,5]

# c-type
index_var = 0

for i in range(len(numbers)):
    fruit = fruits[index_var]
    number = numbers[index_var]
    #index_var = index_var + 1
    index_var += 1
    print(f"you get {number}, {fruit}")

you get 1, oranges
you get 2, pineapples
you get 3, apples
you get 4, bananas
you get 5, strawberries


In [3]:
len(numbers)


5

In [6]:
for fruit, number in zip(fruits,numbers):
    print(f"you get {number}, {fruit}")

you get 1, oranges
you get 2, pineapples
you get 3, apples
you get 4, bananas
you get 5, strawberries


In [16]:
# if statements
condition1 = True
condition2 = True
condition3 = True
condition4 = False

if condition1: # condition1 == True
    # body of if block
    print("we are in the if statement block!")
elif condition2 == True:
    print("we are in the first elif statement block!")
elif condition3 == True:
    print("we are in the third elif statement block!")
else:
    print("None was true!")
    

we are in the if statement block!


In [9]:
condition1 == True

True

In [17]:
5 > 1

True

In [18]:
'hello' == "Hello"

False

In [19]:
'hello' == "hello"

True

In [20]:
1>=0

True

In [21]:
my_age = 19

In [23]:
my_age >=18 and my_age<25 

True

In [28]:
(my_age >=18 and my_age<25) or (my_age%2) == 0

True

In [24]:
my_age%2

1

In [27]:
(my_age >=18 and my_age<25) and (my_age%2) == 0

False

In [29]:
5 != 5

False

In [30]:
5==5

True

In [31]:
not 5==5

False

In [33]:
my_age2 = 4

In [39]:
if (-1) or False:
    print("True")
else:
    print("Not true")

True


In [40]:
import numpy as np

In [41]:
my_array = np.random.rand(10)
my_array

array([0.80285199, 0.4280548 , 0.68884273, 0.16796992, 0.80177694,
       0.232418  , 0.5928286 , 0.37357015, 0.68678321, 0.42558025])

In [43]:
my_array *= 100
my_array

array([80.28519855, 42.80547977, 68.8842733 , 16.79699233, 80.1776945 ,
       23.24180009, 59.28286037, 37.35701455, 68.6783212 , 42.55802527])

In [44]:
total = 0 #accumulator
for item in my_array:
    total += item
    print(f"{item} {total}")

80.28519854606914 80.28519854606914
42.805479771457875 123.09067831752702
68.88427330455447 191.9749516220815
16.79699232835741 208.77194395043892
80.17769449735285 288.94963844779176
23.24180009181902 312.1914385396108
59.282860366695324 371.4742989063061
37.35701455045392 408.83131345676003
68.67832119768705 477.5096346544471
42.55802527392218 520.0676599283693


In [45]:
total = sum(my_array)
print(total)

520.0676599283693


In [47]:
total = 0
for item in my_array:
    if item >= 50:
        total+=item
        print(f"{item} {total}")    
        
print(total)

80.28519854606914 80.28519854606914
68.88427330455447 149.1694718506236
80.17769449735285 229.34716634797644
59.282860366695324 288.63002671467177
68.67832119768705 357.30834791235884
357.30834791235884


In [48]:
total = 0
for item in my_array:
    if item < 50:
        continue # goes to next iteration
    total+=item
    print(f"{item} {total}") 

80.28519854606914 80.28519854606914
68.88427330455447 149.1694718506236
80.17769449735285 229.34716634797644
59.282860366695324 288.63002671467177
68.67832119768705 357.30834791235884


In [50]:
# total = 0 if we have a zero!
my_array[5] = 0
total = 0
for item in my_array:
    if item == 0:
        print("Bad egg!")
        break
    else:
        total+=item
        print(f"{item} {total}") 
        total = 0
print(total)
        

80.28519854606914 80.28519854606914
42.805479771457875 42.805479771457875
68.88427330455447 68.88427330455447
16.79699232835741 16.79699232835741
80.17769449735285 80.17769449735285
Bad egg!
0


In [51]:
my_array

array([80.28519855, 42.80547977, 68.8842733 , 16.79699233, 80.1776945 ,
        0.        , 59.28286037, 37.35701455, 68.6783212 , 42.55802527])

In [52]:
import numpy as np

In [53]:
#conda install numpy

In [54]:
total = 0
remainder = 0
while total < 500:
    total += np.random.randint(0,100)
    print(f"{total} {remainder}")
    if total > 500:
        remainder = total - 500
        total = 500
print ("we are outside the while loop")
print(f"{total} {remainder}")
    

51 0
89 0
104 0
198 0
245 0
303 0
334 0
347 0
375 0
383 0
385 0
406 0
439 0
537 0
we are outside the while loop
500 37


In [55]:
myset = {1,2,3}
myset2 = {3,4,5}

In [56]:
my_dict = {1:'one', 2:'hello', 3:'three', 4:[1,2,3,4,5]}

In [57]:
my_dict

{1: 'one', 2: 'hello', 3: 'three', 4: [1, 2, 3, 4, 5]}

In [58]:
my_dict['string_key'] = 'new_value'

In [59]:
my_dict

{1: 'one',
 2: 'hello',
 3: 'three',
 4: [1, 2, 3, 4, 5],
 'string_key': 'new_value'}

In [60]:
my_dict[1] = 1

In [61]:
my_dict

{1: 1, 2: 'hello', 3: 'three', 4: [1, 2, 3, 4, 5], 'string_key': 'new_value'}

In [62]:
fruits


['oranges', 'pineapples', 'apples', 'bananas', 'strawberries']

In [63]:
numbers

[1, 2, 3, 4, 5]

In [64]:
dict2 = dict(zip(numbers, fruits))

In [65]:
dict2

{1: 'oranges', 2: 'pineapples', 3: 'apples', 4: 'bananas', 5: 'strawberries'}

In [66]:
keys = dict2.keys()

In [67]:
keys

dict_keys([1, 2, 3, 4, 5])

In [69]:
keylist = list(keys)

In [70]:
keylist

[1, 2, 3, 4, 5]

In [71]:
dict2.values()

dict_values(['oranges', 'pineapples', 'apples', 'bananas', 'strawberries'])

In [72]:
#iterate through a dictionary
for keyVar, valueVar in dict2.items():
    print(keyVar, valueVar)

1 oranges
2 pineapples
3 apples
4 bananas
5 strawberries


In [73]:
# class exercise

destinations = {'New York': 821, 'New orleans': 540.7, 'Chicago':779, 'Victoria':2872}

In [74]:
destinations


{'New York': 821, 'New orleans': 540.7, 'Chicago': 779, 'Victoria': 2872}

In [75]:
cost_per_mile = 0.01 # $ 

In [2]:
# get input from user. quit if q or Q
cost_per_mile = 0.01 # $ 
destinations = {'New York': 821, 'New orleans': 540.7, 'Chicago':779, 'Victoria':2872}
user_destination = input("Where would you like to travel to? Q|q to quit").upper()
upper_destinations = {} 
# convert keys to uppercase
for key,value in destinations.items():
    upper_destinations[key.upper()] = value
while user_destination != 'Q':
    if user_destination in upper_destinations:
        print(f"Athens to {user_destination} costs {cost_per_mile * upper_destinations[user_destination]} $")
    else:
        print(f"Destination not available, yet!")
    
    user_destination = input("Where would you like to travel to? Q|q to quit").upper()
    
    
print("Thanks for flying INFO2000!")

Where would you like to travel to? Q|q to quit New YOrk


Athens to NEW YORK costs 8.21 $


Where would you like to travel to? Q|q to quit Gainesville


Destination not available, yet!


Where would you like to travel to? Q|q to quit q


Thanks for flying INFO2000!


In [79]:
821 in destinations

False

In [82]:
'NEW YORK' in destinations

False

In [ ]:
# get input from user. quit if q or Q
destinations = {'New York': 821, 'New orleans': 540.7, 'Chicago':779, 'Victoria':2872}
user_destination = input("Where would you like to travel to? Q|q to quit").upper()
upper_destinations = {} 
# convert keys to uppercase
for key,value in destinations.items():
    upper_destinations[key.upper()] = value
while user_destination != 'Q':
    if user_destination in upper_destinations:
        print(f"Athens to {user_destination} costs {cost_per_mile * upper_destinations[user_destination]} $")
    else:
        print(f"Destination not available, yet!")
        add = input("Add destination? y ")
        # get user input
        
        # if user input == 'Y':
           # dest = userinput
            #miles = userinput
            #dest[userinput] = miles
        else:
        
    
    user_destination = input("Where would you like to travel to? Q|q to quit").upper()
    
    
print("Thanks for flying INFO2000!")

Where would you like to travel to? Q|q to quit Gainesville


Destination not available, yet!


Add destination? y|N  n
Where would you like to travel next? Q|q to quit Gainesville


Destination not available, yet!


Add destination? y|N  y
What's the distance between Athens and GAINESVILLE in miles? 45
Where would you like to travel next? Q|q to quit gainesville


Athens to GAINESVILLE costs 0.45 $
